import { Fragment } from 'react'

/**
 * Detects if body content is HTML (from the Quill rich text editor)
 * vs markdown-style plain text (legacy format).
 */
function isHtmlContent(body: string[]): boolean {
  if (!Array.isArray(body) || body.length === 0) return false
  // If there's only one element and it contains HTML tags, treat as HTML
  if (body.length === 1) {
    return /<[a-z][\s\S]*>/i.test(body[0])
  }
  // Multi-element arrays are always treated as markdown-style blocks
  return false
}

function tryParseJsonArray(maybeJson: string): string[] | null {
  const str = (maybeJson ?? '').trim()
  if (!str) return null
  if (!((str.startsWith('[') && str.endsWith(']')) || (str.startsWith('"[') && str.endsWith(']"')))) {
    return null
  }

  try {
    const parsed = JSON.parse(str)
    if (Array.isArray(parsed)) return parsed.map((s) => String(s))
  } catch {
    // ignore
  }

  // Handle a second layer of quoting: "[\"<p>...</p>\"]" (double-encoded)
  if (str.startsWith('"[') && str.endsWith(']"')) {
    try {
      const unquoted = JSON.parse(str) // becomes ["<p>...</p>"]
      const parsed2 = JSON.parse(unquoted)
      if (Array.isArray(parsed2)) return parsed2.map((s) => String(s))
    } catch {
      // ignore
    }
  }

  // If it's already JSON for an array, but not detected above, don't render raw.
  // We already attempted JSON.parse for the first layer; returning null falls back to legacy.
  return null
}


/**
 * Renders a blog body that may contain either:
 * - Markdown-style plain text (headings starting with #, ##, ###, bullet lists, paragraphs)
 * - Full HTML content generated by the Quill rich text editor
 */
export function renderBlogBody(body: string[]) {
  if (!Array.isArray(body) || body.length === 0) return null

  // Sometimes Quill HTML gets stored as a stringified JSON array.
  // If the single element looks like JSON, parse it so we render the HTML,
  // not the literal ["..."].
  if (body.length === 1) {
    const parsed = tryParseJsonArray(body[0])
    if (parsed && parsed.length > 0) {
      body = parsed
    }
  }

  // If it's HTML content, render it directly with dangerouslySetInnerHTML
  if (isHtmlContent(body)) {
    return (
      <div className="blog-body-html" dangerouslySetInnerHTML={{ __html: body[0] }} />
    )
  }


  // Legacy markdown-style rendering
  const nodes: React.ReactNode[] = []

  for (let i = 0; i < body.length; i++) {
    const raw = body[i]
    const line = (raw ?? '').toString().trimStart().trimEnd()
    if (!line) continue

    // Headings (markdown-like)
    if (line.startsWith('### ')) {
      nodes.push(
        <h4 key={`h4-${i}`} className="article-h4">
          {line.slice(4).trim()}
        </h4>,
      )
      continue
    }
    if (line.startsWith('## ')) {
      nodes.push(
        <h3 key={`h3-${i}`} className="article-h3">
          {line.slice(3).trim()}
        </h3>,
      )
      continue
    }
    if (line.startsWith('# ')) {
      nodes.push(
        <h2 key={`h2-${i}`} className="article-h2">
          {line.slice(2).trim()}
        </h2>,
      )
      continue
    }

    // Bullet list (contiguous lines)
    if (line.startsWith('- ') || line.startsWith('* ')) {
      const items: string[] = []
      let j = i
      while (j < body.length) {
        const candidate = (body[j] ?? '').toString().trim()
        if (!candidate) break
        if (candidate.startsWith('- ') || candidate.startsWith('* ')) {
          items.push(candidate.slice(2).trim())
          j++
          continue
        }
        break
      }

      nodes.push(
        <ul key={`ul-${i}`} className="article-ul">
          {items.map((it, idx) => (
            <li key={`li-${i}-${idx}`}>{it}</li>
          ))}
        </ul>,
      )

      i = j - 1
      continue
    }

    // Default paragraph
    nodes.push(
      <p key={`p-${i}`} className="article-p">
        {line}
      </p>,
    )
  }

  return <Fragment>{nodes}</Fragment>
}